@startuml
title Peminjaman Fasilitas
!theme mars
|Mahasiswa|
start
:Memilih fasilitas;
:Memasukkan NPM;
:Mengisi deskripsi, jenis, dan jumlah \npeserta kegiatan;
:Mengunggah dokumen pendukung \n(surat izin / proposal);
:Memilih waktu mulai, tanggal mulai, \nwaktu selesai, tanggal selesai;
if (waktu mulai >= 3) is (yes) then
    |#AntiqueWhite|Staf Fasilitas|
    :Mengevaluasi peminjaman;
    :Mengecek ketersediaan fasilitas;
    if (fasilitas tersedia?) is (yes) then
        :Memastikan jadwal peminjaman;
        if (bentrok dengan KBM?) is (yes) then
            :Pengajuan ditolak;
            stop
        else (no)
            :Pengajuan diterima;
            stop
        endif
    else (no)
        :Pengajuan ditolak;
        stop
    endif
else (no)
    |Staf Fasilitas|
    :Pengajuan ditolak;
    stop
endif
@enduml